POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title" : "another note again",
    "author" : "neggtacci",
    "url" : "jhhdhd",
    "likes" : "6",
    "userId": "620d0a41dcfcaf11efe8c5dc"
}